import React from 'react';
import { GraduationCap, Globe, Flame, Sparkles } from 'lucide-react';

export const UI_STRINGS = {
  de: {
    COMMON: {
      APP_NAME: "Voka bro",
      SAVE: "Speichern",
      CANCEL: "Abbrechen",
      DELETE: "Löschen",
      BACK: "Zurück",
      CLOSE: "Schließen",
      LOADING: "Lädt...",
      ERROR: "Fehler",
      SUCCESS: "Erfolg",
      ADD: "Hinzufügen",
      EDIT: "Bearbeiten",
      SEARCH: "Suchen...",
      DEUTSCH: "Deutsch",
      FOREIGN_LANG: "Fremdsprache",
      LOGOUT: "Abmelden",
      YES_DELETE: "Ja, löschen",
      SELECT_LANGUAGE: "Sprache auswählen",
      CHOOSE_LANGUAGE: "Wähle eine Sprache...",
      ADD_LANGUAGE: "Sprache hinzufügen",
      PREDEFINED_LANGUAGES: [
        { code: 'en', name: 'Englisch', flag: '🇬🇧' },
        { code: 'es', name: 'Spanisch', flag: '🇪🇸' },
        { code: 'fr', name: 'Französisch', flag: '🇫🇷' },
        { code: 'it', name: 'Italienisch', flag: '🇮🇹' },
        { code: 'pt', name: 'Portugiesisch', flag: '🇵🇹' },
        { code: 'ru', name: 'Russisch', flag: '🇷🇺' },
        { code: 'tr', name: 'Türkisch', flag: '🇹🇷' },
        { code: 'pl', name: 'Polnisch', flag: '🇵🇱' },
        { code: 'nl', name: 'Niederländisch', flag: '🇳🇱' },
      ],
    },
    LANDING: {
      TAGLINE: "Die einfache Art, Sprachen zu lernen. Effektiv, schnell und motivierend.",
      START_BUTTON: "Jetzt loslegen",
      FEATURES: [
        {
          icon: <GraduationCap className="text-primary" size={24} />,
          title: "Intelligentes Lernen",
          description: "Vokabeln mit Hilfe von Karteikarten lernen"
        },
        {
          icon: <Globe className="text-secondary" size={24} />,
          title: "Multi-Language",
          description: "Lerne mehrere Sprachen gleichzeitig mit automatischer Spracherkennung."
        },
        {
          icon: <Flame className="text-orange-500" size={24} />,
          title: "Lern-Serie",
          description: "Bleib motiviert mit täglichen Streaks und Statistiken."
        },
        {
          icon: <Sparkles className="text-success" size={24} />,
          title: "Modernes UI",
          description: "Ein sauberes, schnelles Interface für maximale Konzentration."
        }
      ],
      SOCIAL_PROOF: "Bereits +1000 Vokabeln gelernt",
      FOOTER_INFO: "Kostenlos nutzen • Keine Werbung",
    },
    LOGIN: {
      SUBTITLE_LOGIN: "Melde dich an",
      SUBTITLE_SIGNUP: "Erstelle ein Konto",
      SUBTITLE_FORGOT: "Passwort zurücksetzen",
      EMAIL_LABEL: "E-Mail",
      EMAIL_PLACEHOLDER: "deine@email.de",
      PASSWORD_LABEL: "Passwort",
      PASSWORD_PLACEHOLDER: "••••••••",
      FORGOT_PASSWORD: "Vergessen?",
      LOGIN_BUTTON: "Anmelden",
      SIGNUP_BUTTON: "Registrieren",
      SEND_LINK: "Link senden",
      SIGNUP_PROMPT: "Noch kein Konto? Registrieren",
      LOGIN_PROMPT: "Bereits ein Konto? Anmelden",
      BACK_TO_LOGIN: "Zurück zum Login",
      SUCCESS_SIGNUP: "Registrierung erfolgreich! Bitte prüfe deine E-Mails.",
      SUCCESS_FORGOT: "E-Mail zum Zurücksetzen wurde gesendet!",
      ERR_INVALID_CREDENTIALS: "Ungültige Anmeldedaten. Bitte prüfe E-Mail und Passwort.",
      ERR_ALREADY_REGISTERED: "Diese E-Mail-Adresse ist bereits registriert.",
      ERR_PASSWORD_SHORT: "Das Passwort muss mindestens 6 Zeichen lang sein.",
    },
    LEARNING: {
      TITLE: "Lernen",
      TITLE_ARCHIVE: "Archiv Wiederholen",
      ONBOARDING_TITLE: "Willkommen!",
      ONBOARDING_SUBTITLE: "Wähle eine Sprache aus, um mit dem Lernen zu beginnen.",
      LOADING_VOKABELN: "Lade Vokabeln...",
      SESSION_COMPLETED: "Session beendet!",
      ALL_LEARNED: "Alles gelernt!",
      SESSION_STATS: (count, errors) => `Du hast ${count} Vokabeln gelernt.${errors > 0 ? ` Dabei gab es ${errors} Fehler.` : ''}`,
      EMPTY_STATE: "Alle Vokabeln sind im Archiv oder du hast noch keine hinzugefügt.",
      NEW_SESSION: "Neue Session",
      REFRESH: "Aktualisieren",
      ARCHIVE_REPEAT: "Archivierte Vokabeln wiederholen (Random)",
      ERRORS_OVERVIEW: "Deine Fehler im Überblick",
      RIGHT_ANSWER: "Richtig wäre",
      CHECK_BUTTON: "Prüfen",
      NEXT_BUTTON: "Weiter",
      DONT_KNOW_BUTTON: "Ich weiß es nicht",
      TOO_SOON_MSG: "Richtig! (Status unverändert - 12h Regel)",
      STATUS_UP_MSG: "Sehr gut! +1 Status",
      STREAK_INFO_TITLE: "Streak",
      STREAK_INFO_TEXT: "Deine Serie an aufeinanderfolgenden Lerntagen!",
      MIC_ERR_NOT_SUPPORTED: "Spracherkennung wird in diesem Browser nicht unterstützt.",
      INPUT_PLACEHOLDER: "Hier schreiben...",
      LISTENING_PLACEHOLDER: "Höre zu...",
      MIC_ERROR: "Spracherkennung wird in diesem Browser nicht unterstützt.",
      UPDATE_FAILED: "Update fehlgeschlagen:",
      ACCENT_WARNING_TITLE: "Fast richtig!",
      ACCENT_WARNING_TEXT: "Nur ein Akzent ist falsch. Du hast noch einen Versuch!",
    },
    OVERVIEW: {
      TITLE: "Übersicht",
      SEARCH_PLACEHOLDER: "Suchen...",
      SORT_ALPHA: "Nach Alphabet sortieren",
      SORT_DATE: "Nach Datum sortieren",
      ARCHIVE_HEADER: "Archiv",
      EMPTY_STATE: "Keine Vokabeln gefunden",
      MODAL_ADD_TITLE: "Neue Vokabel",
      MODAL_EDIT_TITLE: "Vokabel bearbeiten",
      GERMAN_LABEL: "Deutsch",
      GERMAN_PLACEHOLDER: "z.B. Apfel",
      FOREIGN_LABEL: "Fremdsprache",
      FOREIGN_PLACEHOLDER: "z.B. apple",
      ERR_FILL_ALL: "Bitte beide Felder ausfüllen",
      ERR_SAVE: "Konnte Vokabel nicht speichern",
      ERR_DELETE: "Konnte Vokabel nicht löschen",
      EMPTY_STATE_SUB: "Füge deine ersten Vokabeln hinzu, um zu starten.",
      NO_LANGUAGE_TITLE: "Keine Sprache ausgewählt",
      NO_LANGUAGE_SUB: "Bitte füge zuerst eine Sprache in deinem Profil hinzu.",
      GO_TO_PROFILE: "Zum Profil",
      ARCHIVE_TAG: "ARCHIV",
      VERB_LABEL: "Verb konjugieren?",
      REFLEXIVE_LABEL: "Reflexiv?",
      REFLEXIVE_DESC: "Fügt Pronomen wie 'me', 'te', 'se' als Merkhilfe hinzu (z.B. llamarse -> me llamo).",
      INFINITIVE_LABEL: "Infinitiv",
      YO: "yo",
      TU: "tú",
      EL: "él/ella",
      NOSOTROS: "nosotros",
      VOSOTROS: "vosotros",
      ELLOS: "ellos/ellas",
    },
    PROFILE: {
      TITLE: "Profil & Einstellungen",
      SUPERADMIN_TAG: "Superadmin",
      LANGUAGES_SECTION: "Meine Sprachen",
      ADD_LANGUAGE_LABEL: "Sprache auswählen",
      ADD_LANGUAGE_PLACEHOLDER: "Wähle eine neue Sprache...",
      ADD_LANGUAGE_BUTTON: "Sprache hinzufügen",
      UI_LANGUAGE_SECTION: "App Sprache",
      STATS_SECTION: "Statistik",
      STATS_TOTAL: "Gesamt",
      STATS_LEARNED: "Gelernt",
      STATS_OPEN: "Offen",
      ACTIVITY_SECTION: "Lernaktivität",
      STREAK_DAYS: (days) => `${days} Tage Serie`,
      NAME_LABEL: "Name",
      NAME_PLACEHOLDER: "Dein Name",
      EMAIL_LABEL: "E-Mail",
      EMAIL_PLACEHOLDER: "deine@email.de",
      CHANGE_PASSWORD: "Passwort ändern",
      SUPERADMIN_SETTINGS: "Superadmin Einstellungen",
      DISABLE_TOO_SOON_LABEL: "12h Sperre deaktivieren",
      DISABLE_TOO_SOON_DESC: "Erlaubt das sofortige Hochstufen von Vokabeln",
      USER_ID_LABEL: "User ID:",
      SUCCESS_UPDATE: "Profil erfolgreich aktualisiert!",
      ERR_EMAIL_EXISTS: "Diese E-Mail-Adresse wird bereits verwendet.",
      DELETE_LANG_TITLE: "Sprache löschen?",
      DELETE_LANG_DESC: "Möchtest du diese Sprache wirklich löschen? Alle zugehörigen Vokabeln gehen verloren.",
      WEEKDAYS: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
    },
    COMPONENTS: {
      DELETE_MODAL: {
        TITLE: "Vokabel löschen?",
        DESC: "Möchtest du diese Vokabel wirklich unwiderruflich löschen?",
        CONFIRM: "Ja, löschen",
      },
      PASSWORD_MODAL: {
        TITLE: "Passwort ändern",
        CURRENT_LABEL: "Aktuelles Passwort",
        NEW_LABEL: "Neues Passwort",
        CONFIRM_LABEL: "Passwort bestätigen",
        SUCCESS: "Passwort erfolgreich geändert!",
        ERR_MISMATCH: "Die neuen Passwörter stimmen nicht überein.",
        ERR_SHORT: "Das Passwort muss mindestens 6 Zeichen lang sein.",
        ERR_OLD_WRONG: "Das alte Passwort ist nicht korrekt.",
        UPDATE_BUTTON: "Passwort aktualisieren",
      }
    }
  },
  en: {
    COMMON: {
      APP_NAME: "Voka bro",
      SAVE: "Save",
      CANCEL: "Cancel",
      DELETE: "Delete",
      BACK: "Back",
      CLOSE: "Close",
      LOADING: "Loading...",
      ERROR: "Error",
      SUCCESS: "Success",
      ADD: "Add",
      EDIT: "Edit",
      SEARCH: "Search...",
      DEUTSCH: "German",
      FOREIGN_LANG: "Foreign Language",
      LOGOUT: "Logout",
      YES_DELETE: "Yes, delete",
      SELECT_LANGUAGE: "Select language",
      CHOOSE_LANGUAGE: "Choose a language...",
      ADD_LANGUAGE: "Add language",
      PREDEFINED_LANGUAGES: [
        { code: 'en', name: 'English', flag: '🇬🇧' },
        { code: 'es', name: 'Spanish', flag: '🇪🇸' },
        { code: 'fr', name: 'French', flag: '🇫🇷' },
        { code: 'it', name: 'Italian', flag: '🇮🇹' },
        { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
        { code: 'ru', name: 'Russian', flag: '🇷🇺' },
        { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
        { code: 'pl', name: 'Polish', flag: '🇵🇱' },
        { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
      ],
    },
    LANDING: {
      TAGLINE: "The easy way to learn languages. Effective, fast, and motivating.",
      START_BUTTON: "Start now",
      FEATURES: [
        {
          icon: <GraduationCap className="text-primary" size={24} />,
          title: "Intelligent Learning",
          description: "Learn vocabulary based on your progress. Status 0 to 5 (Archived)."
        },
        {
          icon: <Globe className="text-secondary" size={24} />,
          title: "Multi-Language",
          description: "Learn multiple languages simultaneously with automatic language detection."
        },
        {
          icon: <Flame className="text-orange-500" size={24} />,
          title: "Learning Streak",
          description: "Stay motivated with daily streaks and statistics."
        },
        {
          icon: <Sparkles className="text-success" size={24} />,
          title: "Modern UI",
          description: "A clean, fast interface for maximum concentration."
        }
      ],
      SOCIAL_PROOF: "Over 1000 words learned",
      FOOTER_INFO: "Free to use • No ads",
    },
    LOGIN: {
      SUBTITLE_LOGIN: "Sign in",
      SUBTITLE_SIGNUP: "Create an account",
      SUBTITLE_FORGOT: "Reset password",
      EMAIL_LABEL: "Email",
      EMAIL_PLACEHOLDER: "your@email.com",
      PASSWORD_LABEL: "Password",
      PASSWORD_PLACEHOLDER: "••••••••",
      FORGOT_PASSWORD: "Forgot?",
      LOGIN_BUTTON: "Sign In",
      SIGNUP_BUTTON: "Sign Up",
      SEND_LINK: "Send Link",
      SIGNUP_PROMPT: "Don't have an account? Sign Up",
      LOGIN_PROMPT: "Already have an account? Sign In",
      BACK_TO_LOGIN: "Back to Login",
      SUCCESS_SIGNUP: "Registration successful! Please check your emails.",
      SUCCESS_FORGOT: "Reset email has been sent!",
      ERR_INVALID_CREDENTIALS: "Invalid credentials. Please check email and password.",
      ERR_ALREADY_REGISTERED: "This email address is already registered.",
      ERR_PASSWORD_SHORT: "The password must be at least 6 characters long.",
    },
    LEARNING: {
      TITLE: "Learn",
      TITLE_ARCHIVE: "Review Archive",
      ONBOARDING_TITLE: "Welcome!",
      ONBOARDING_SUBTITLE: "Choose a language to start learning.",
      LOADING_VOKABELN: "Loading vocabulary...",
      SESSION_COMPLETED: "Session finished!",
      ALL_LEARNED: "All learned!",
      SESSION_STATS: (count, errors) => `You learned ${count} words.${errors > 0 ? ` There were ${errors} errors.` : ''}`,
      EMPTY_STATE: "All words are in the archive or you haven't added any yet.",
      NEW_SESSION: "New Session",
      REFRESH: "Refresh",
      ARCHIVE_REPEAT: "Review archived words (Random)",
      ERRORS_OVERVIEW: "Your errors at a glance",
      RIGHT_ANSWER: "Correct answer",
      CHECK_BUTTON: "Check",
      NEXT_BUTTON: "Next",
      DONT_KNOW_BUTTON: "I don't know",
      TOO_SOON_MSG: "Correct! (Status unchanged - 12h rule)",
      STATUS_UP_MSG: "Very good! +1 Status",
      STREAK_INFO_TITLE: "Streak",
      STREAK_INFO_TEXT: "Your series of consecutive learning days!",
      MIC_ERR_NOT_SUPPORTED: "Speech recognition is not supported in this browser.",
      INPUT_PLACEHOLDER: "Write here...",
      LISTENING_PLACEHOLDER: "Listening...",
      MIC_ERROR: "Speech recognition is not supported in this browser.",
      UPDATE_FAILED: "Update failed:",
      ACCENT_WARNING_TITLE: "Almost correct!",
      ACCENT_WARNING_TEXT: "Just an accent is wrong. You have one more try!",
    },
    OVERVIEW: {
      TITLE: "Overview",
      SEARCH_PLACEHOLDER: "Search...",
      SORT_ALPHA: "Sort alphabetically",
      SORT_DATE: "Sort by date",
      ARCHIVE_HEADER: "Archive",
      EMPTY_STATE: "No words found",
      MODAL_ADD_TITLE: "New Vocabulary",
      MODAL_EDIT_TITLE: "Edit Vocabulary",
      GERMAN_LABEL: "German",
      GERMAN_PLACEHOLDER: "e.g. apple",
      FOREIGN_LABEL: "Foreign Language",
      FOREIGN_PLACEHOLDER: "e.g. apple",
      ERR_FILL_ALL: "Please fill both fields",
      ERR_SAVE: "Could not save vocabulary",
      ERR_DELETE: "Could not delete vocabulary",
      EMPTY_STATE_SUB: "Add your first words to get started.",
      NO_LANGUAGE_TITLE: "No language selected",
      NO_LANGUAGE_SUB: "Please add a language in your profile first.",
      GO_TO_PROFILE: "Go to Profile",
      ARCHIVE_TAG: "ARCHIVE",
      VERB_LABEL: "Conjugate verb?",
      REFLEXIVE_LABEL: "Reflexive?",
      REFLEXIVE_DESC: "Adds pronouns like 'me', 'te', 'se' as a memory aid (e.g., llamarse -> me llamo).",
      INFINITIVE_LABEL: "Infinitive",
      YO: "I",
      TU: "you",
      EL: "he/she/it",
      NOSOTROS: "we",
      VOSOTROS: "you (all)",
      ELLOS: "they",
    },
    PROFILE: {
      TITLE: "Profile & Settings",
      SUPERADMIN_TAG: "Superadmin",
      LANGUAGES_SECTION: "My Languages",
      ADD_LANGUAGE_LABEL: "Select language",
      ADD_LANGUAGE_PLACEHOLDER: "Choose a new language...",
      ADD_LANGUAGE_BUTTON: "Add language",
      UI_LANGUAGE_SECTION: "App Language",
      STATS_SECTION: "Statistics",
      STATS_TOTAL: "Total",
      STATS_LEARNED: "Learned",
      STATS_OPEN: "Open",
      ACTIVITY_SECTION: "Study Activity",
      STREAK_DAYS: (days) => `${days} Days Streak`,
      NAME_LABEL: "Name",
      NAME_PLACEHOLDER: "Your Name",
      EMAIL_LABEL: "Email",
      EMAIL_PLACEHOLDER: "your@email.com",
      CHANGE_PASSWORD: "Change Password",
      SUPERADMIN_SETTINGS: "Superadmin Settings",
      DISABLE_TOO_SOON_LABEL: "Disable 12h Lock",
      DISABLE_TOO_SOON_DESC: "Allows immediate leveling up of vocabulary",
      USER_ID_LABEL: "User ID:",
      SUCCESS_UPDATE: "Profile updated successfully!",
      ERR_EMAIL_EXISTS: "This email address is already in use.",
      DELETE_LANG_TITLE: "Delete language?",
      DELETE_LANG_DESC: "Do you really want to delete this language? All associated vocabulary will be lost.",
      WEEKDAYS: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    },
    COMPONENTS: {
      DELETE_MODAL: {
        TITLE: "Delete vocabulary?",
        DESC: "Do you really want to permanently delete this vocabulary?",
        CONFIRM: "Yes, delete",
      },
      PASSWORD_MODAL: {
        TITLE: "Change password",
        CURRENT_LABEL: "Current password",
        NEW_LABEL: "New password",
        CONFIRM_LABEL: "Confirm password",
        SUCCESS: "Password successfully changed!",
        ERR_MISMATCH: "The new passwords do not match.",
        ERR_SHORT: "The password must be at least 6 characters long.",
        ERR_OLD_WRONG: "The old password is not correct.",
        UPDATE_BUTTON: "Update password",
      }
    }
  }
};
